'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';

export function TeamWorkspace() {
  const [showCreate, setShowCreate] = useState(false);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const teamsQuery = useQuery({ queryKey: ['teams'], queryFn: async () => { const response = await fetch('/api/teams'); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? 'Could not load teams'); return body.data as Array<{ team: { id: string; name: string; description: string | null; status: string; maxMembers: number }; membership: { role: string | null } }>; } });
  async function createTeam() { const response = await fetch('/api/teams', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, description, maxMembers: 4, rolesNeeded: [], isOpen: true }) }); if (response.ok) { setName(''); setDescription(''); setShowCreate(false); void teamsQuery.refetch(); } }
  return <div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Collaboration</p><h1 className="mt-2 text-4xl font-bold">My teams</h1><p className="mt-3 text-slate-600">Create a team, then invite builders or accept applications.</p></div><button onClick={() => setShowCreate((value) => !value)} className="rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white">Create team</button></div>{showCreate && <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><div className="grid gap-4 sm:grid-cols-2"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Team name" className="input" /><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What are you building?" className="input" /></div><button onClick={() => void createTeam()} disabled={!name.trim()} className="mt-5 rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">Save team</button></div>}{teamsQuery.isLoading && <p className="mt-10 text-slate-500">Loading teams…</p>}{teamsQuery.error && <div className="mt-10 rounded-xl bg-amber-50 p-5 text-amber-800">{teamsQuery.error.message}</div>}<div className="mt-8 grid gap-5 md:grid-cols-2">{teamsQuery.data?.length ? teamsQuery.data.map(({ team, membership }) => <Link key={team.id} href={`/teams/${team.id}`} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-md"><div className="flex items-start justify-between gap-4"><h2 className="text-xl font-bold">{team.name}</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{team.status}</span></div><p className="mt-3 text-sm text-slate-600">{team.description ?? 'No description yet.'}</p><p className="mt-5 text-sm text-slate-500">Your role: {membership.role ?? 'member'} · Max {team.maxMembers} members</p></Link>) : !teamsQuery.isLoading && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">You are not on a team yet.</div>}</div></div>;
}
