'use client';

import { useQuery } from '@tanstack/react-query';

export function RequestInbox() {
  const query = useQuery({ queryKey: ['requests'], queryFn: async () => { const response = await fetch('/api/requests?direction=all'); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? 'Could not load requests'); return body.data as Array<{ request: { id: string; status: string; message: string | null; fromUserId: string; toUserId: string }; from: { username: string; fullName: string | null }; team: { name: string } | null }>; } });
  async function act(id: string, action: 'accept' | 'reject' | 'withdraw') { const response = await fetch(`/api/requests/${id}/${action}`, { method: 'POST' }); if (response.ok) void query.refetch(); }
  if (query.isLoading) return <p className="text-slate-500">Loading requests…</p>;
  if (query.error) return <div className="rounded-xl bg-amber-50 p-5 text-amber-800">{query.error.message}</div>;
  return <div className="mx-auto max-w-4xl"><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Collaboration</p><h1 className="mt-2 text-4xl font-bold">Requests</h1><div className="mt-8 space-y-4">{query.data?.length ? query.data.map(({ request, from, team }) => <div key={request.id} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold text-slate-900">{from.fullName ?? from.username}</p><p className="text-sm text-slate-500">@{from.username}{team ? ` · ${team.name}` : ''}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold uppercase text-slate-500">{request.status}</span></div>{request.message && <p className="mt-4 text-sm leading-6 text-slate-600">{request.message}</p>}{request.status === 'pending' && <div className="mt-5 flex flex-wrap gap-3"><button onClick={() => void act(request.id, 'accept')} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Accept</button><button onClick={() => void act(request.id, 'reject')} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Reject</button><button onClick={() => void act(request.id, 'withdraw')} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Withdraw if sent</button></div>}</div>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No requests yet.</div>}</div></div>;
}
